/* Auto-generated by genmsg_cpp for file /home/robin/Uni/bm/ros_workspace/stacks/cmvision/msg/Blobs.msg */
#ifndef CMVISION_MESSAGE_BLOBS_H
#define CMVISION_MESSAGE_BLOBS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "cmvision/Blob.h"

namespace cmvision
{
template <class ContainerAllocator>
struct Blobs_ {
  typedef Blobs_<ContainerAllocator> Type;

  Blobs_()
  : header()
  , image_width(0)
  , image_height(0)
  , blob_count(0)
  , blobs()
  {
  }

  Blobs_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , image_width(0)
  , image_height(0)
  , blob_count(0)
  , blobs(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint32_t _image_width_type;
  uint32_t image_width;

  typedef uint32_t _image_height_type;
  uint32_t image_height;

  typedef uint32_t _blob_count_type;
  uint32_t blob_count;

  typedef std::vector< ::cmvision::Blob_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cmvision::Blob_<ContainerAllocator> >::other >  _blobs_type;
  std::vector< ::cmvision::Blob_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cmvision::Blob_<ContainerAllocator> >::other >  blobs;


  ROS_DEPRECATED uint32_t get_blobs_size() const { return (uint32_t)blobs.size(); }
  ROS_DEPRECATED void set_blobs_size(uint32_t size) { blobs.resize((size_t)size); }
  ROS_DEPRECATED void get_blobs_vec(std::vector< ::cmvision::Blob_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cmvision::Blob_<ContainerAllocator> >::other > & vec) const { vec = this->blobs; }
  ROS_DEPRECATED void set_blobs_vec(const std::vector< ::cmvision::Blob_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cmvision::Blob_<ContainerAllocator> >::other > & vec) { this->blobs = vec; }
private:
  static const char* __s_getDataType_() { return "cmvision/Blobs"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "9c46147119a8e441f5446a5432b95bda"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
uint32 image_width\n\
uint32 image_height\n\
uint32 blob_count\n\
Blob[] blobs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cmvision/Blob\n\
uint32 red\n\
uint32 green\n\
uint32 blue\n\
uint32 area\n\
uint32 x\n\
uint32 y\n\
uint32 left\n\
uint32 right\n\
uint32 top\n\
uint32 bottom\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, image_width);
    ros::serialization::serialize(stream, image_height);
    ros::serialization::serialize(stream, blob_count);
    ros::serialization::serialize(stream, blobs);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, image_width);
    ros::serialization::deserialize(stream, image_height);
    ros::serialization::deserialize(stream, blob_count);
    ros::serialization::deserialize(stream, blobs);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(image_width);
    size += ros::serialization::serializationLength(image_height);
    size += ros::serialization::serializationLength(blob_count);
    size += ros::serialization::serializationLength(blobs);
    return size;
  }

  typedef boost::shared_ptr< ::cmvision::Blobs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmvision::Blobs_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Blobs
typedef  ::cmvision::Blobs_<std::allocator<void> > Blobs;

typedef boost::shared_ptr< ::cmvision::Blobs> BlobsPtr;
typedef boost::shared_ptr< ::cmvision::Blobs const> BlobsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cmvision::Blobs_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cmvision::Blobs_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cmvision

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cmvision::Blobs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cmvision::Blobs_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cmvision::Blobs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9c46147119a8e441f5446a5432b95bda";
  }

  static const char* value(const  ::cmvision::Blobs_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9c46147119a8e441ULL;
  static const uint64_t static_value2 = 0xf5446a5432b95bdaULL;
};

template<class ContainerAllocator>
struct DataType< ::cmvision::Blobs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cmvision/Blobs";
  }

  static const char* value(const  ::cmvision::Blobs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cmvision::Blobs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
uint32 image_width\n\
uint32 image_height\n\
uint32 blob_count\n\
Blob[] blobs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: cmvision/Blob\n\
uint32 red\n\
uint32 green\n\
uint32 blue\n\
uint32 area\n\
uint32 x\n\
uint32 y\n\
uint32 left\n\
uint32 right\n\
uint32 top\n\
uint32 bottom\n\
\n\
";
  }

  static const char* value(const  ::cmvision::Blobs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::cmvision::Blobs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::cmvision::Blobs_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cmvision::Blobs_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.image_width);
    stream.next(m.image_height);
    stream.next(m.blob_count);
    stream.next(m.blobs);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Blobs_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmvision::Blobs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cmvision::Blobs_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_width);
    s << indent << "image_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_height);
    s << indent << "blob_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.blob_count);
    s << indent << "blobs[]" << std::endl;
    for (size_t i = 0; i < v.blobs.size(); ++i)
    {
      s << indent << "  blobs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cmvision::Blob_<ContainerAllocator> >::stream(s, indent + "    ", v.blobs[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // CMVISION_MESSAGE_BLOBS_H

